"use client";

import React, { useState, useEffect, useRef } from "react";
import { useRouter } from "next/navigation";
import { ProductShell } from "@/components/ui/ProductShell";
import { AuroraBackground } from "@/components/visual/AuroraBackground";
import { Reveal } from "@/components/visual/Reveal";
import { AriCore } from "@/components/visual/AriCore";
import type { DemoCandidateCard } from "@/types/session-dto";
import {
  Briefcase,
  GraduationCap,
  ArrowRight,
  ChevronDown,
  Check,
} from "lucide-react";

const FEATURED_IDS = ["CAND-003", "CAND-004"];

export default function DemoPage() {
  const router = useRouter();
  const [candidates, setCandidates] = useState<DemoCandidateCard[]>([]);
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [isStarting, setIsStarting] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [showAll, setShowAll] = useState(false);

  useEffect(() => {
    async function loadCandidates() {
      try {
        const res = await fetch("/api/demo/candidates");
        const data = await res.json();
        if (data.success) {
          setCandidates(data.candidates);
        } else {
          setError("Failed to load sample profiles.");
        }
      } catch {
        setError("Failed to load sample profiles.");
      } finally {
        setIsLoading(false);
      }
    }
    loadCandidates();
  }, []);

  const handleStart = async () => {
    if (!selectedId || isStarting) return;
    setIsStarting(true);
    setError(null);

    try {
      const res = await fetch("/api/demo/start", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ candidateId: selectedId }),
      });

      const data = await res.json();

      if (!res.ok || !data.success) {
        throw new Error(data.error || "Failed to start session.");
      }

      router.push(`/interview/${data.sessionId}`);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to start session.");
      setIsStarting(false);
    }
  };

  const featured = candidates.filter((c) => FEATURED_IDS.includes(c.id));
  const others = candidates.filter((c) => !FEATURED_IDS.includes(c.id));
  const selectedCandidate = candidates.find((c) => c.id === selectedId);

  return (
    <ProductShell activeRoute="demo">
      <main className="relative flex-1 w-full">
        <AuroraBackground variant="subtle" grid />
        <div className="relative max-w-5xl mx-auto w-full px-4 md:px-8 py-12 md:py-16 space-y-12">
          {/* Header */}
          <Reveal className="text-center space-y-3 max-w-2xl mx-auto">
            <div className="text-[11px] font-mono text-indigo-400 tracking-widest uppercase">
              Experience InterviewOS
            </div>
            <h1 className="text-3xl md:text-4xl font-bold tracking-tight text-zinc-50">
              Same intelligence.{" "}
              <span className="text-aurora">Different starting strategies.</span>
            </h1>
            <p className="text-sm md:text-base text-zinc-500 max-w-lg mx-auto leading-relaxed">
              Select a sample profile to start a fully adaptive technical interview.
              Every question, evaluation, and report is generated by the real engine.
            </p>
          </Reveal>

          {isLoading && (
            <div className="flex items-center justify-center py-20">
              <AriCore state="ready" size={64} />
            </div>
          )}

          {error && !isLoading && (
            <div className="p-4 rounded-lg bg-rose-500/8 border border-rose-500/20 text-rose-300 text-sm max-w-md mx-auto text-center">
              {error}
            </div>
          )}

          {!isLoading && candidates.length > 0 && (
            <>
              {/* Central ARI core branching into two profile journeys */}
              {featured.length > 0 && (
                <div className="space-y-1">
                  {/* Core + animated branches */}
                  <Reveal className="flex flex-col items-center">
                    <AriCore state="active" size={88} />
                    <div className="mt-2 text-center">
                      <span className="text-[10px] font-mono uppercase tracking-widest text-cyan-300">Ari</span>
                      <p className="text-[11px] text-zinc-600 font-mono">one engine · two starting strategies</p>
                    </div>
                    <svg viewBox="0 0 400 70" className="w-full max-w-xl h-16 overflow-visible mt-1" fill="none" aria-hidden="true">
                      <path
                        d="M200 2 C 200 40, 80 30, 80 66"
                        stroke={featured[0]?.id === selectedId ? "#22d3ee" : "rgba(129,140,248,0.35)"}
                        strokeWidth={featured[0]?.id === selectedId ? 2 : 1.4}
                        strokeLinecap="round"
                        className="draw-path is-visible transition-all duration-500"
                        style={{ filter: featured[0]?.id === selectedId ? "drop-shadow(0 0 4px #22d3ee)" : "none" }}
                      />
                      <path
                        d="M200 2 C 200 40, 320 30, 320 66"
                        stroke={featured[1]?.id === selectedId ? "#a78bfa" : "rgba(129,140,248,0.35)"}
                        strokeWidth={featured[1]?.id === selectedId ? 2 : 1.4}
                        strokeLinecap="round"
                        className="draw-path is-visible transition-all duration-500"
                        style={{ filter: featured[1]?.id === selectedId ? "drop-shadow(0 0 4px #a78bfa)" : "none" }}
                      />
                      <circle cx="200" cy="2" r="3" fill="#818cf8" />
                      <circle cx="80" cy="66" r="3" fill={featured[0]?.id === selectedId ? "#22d3ee" : "#3f3f57"} className="transition-all duration-500" />
                      <circle cx="320" cy="66" r="3" fill={featured[1]?.id === selectedId ? "#a78bfa" : "#3f3f57"} className="transition-all duration-500" />
                    </svg>
                  </Reveal>

                  {/* Two profiles */}
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
                    {featured[0] && (
                      <Reveal>
                        <ProfileCard
                          candidate={featured[0]}
                          isSelected={featured[0].id === selectedId}
                          onSelect={() => setSelectedId(featured[0].id)}
                        />
                      </Reveal>
                    )}
                    {featured[1] && (
                      <Reveal delay={80}>
                        <ProfileCard
                          candidate={featured[1]}
                          isSelected={featured[1].id === selectedId}
                          onSelect={() => setSelectedId(featured[1].id)}
                        />
                      </Reveal>
                    )}
                  </div>
                </div>
              )}

              {/* View all */}
              {others.length > 0 && (
                <div className="space-y-4">
                  <button
                    type="button"
                    onClick={() => setShowAll(!showAll)}
                    className="mx-auto flex items-center gap-2 text-xs font-mono text-zinc-600 hover:text-zinc-400 transition-colors"
                  >
                    <ChevronDown className={`h-3 w-3 transition-transform ${showAll ? "rotate-180" : ""}`} />
                    <span>{showAll ? "Hide" : "View all"} sample profiles ({others.length})</span>
                  </button>

                  {showAll && (
                    <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-3 animate-fade-in">
                      {others.map((candidate) => (
                        <ProfileCard
                          key={candidate.id}
                          candidate={candidate}
                          isSelected={candidate.id === selectedId}
                          onSelect={() => setSelectedId(candidate.id)}
                          compact
                        />
                      ))}
                    </div>
                  )}
                </div>
              )}

              {/* Selection → ARI connection panel */}
              {selectedCandidate && (
                <div className="relative rounded-2xl border border-indigo-500/20 bg-[var(--surface)]/70 backdrop-blur-sm p-6 md:p-8 animate-scale-in overflow-hidden">
                  <div className="beam opacity-40" />
                  <div className="relative flex flex-col md:flex-row items-center gap-6 md:gap-8">
                    {/* Candidate → ARI visual link */}
                    <div className="flex items-center gap-4 shrink-0">
                      <div className="text-right">
                        <p className="text-sm font-semibold text-zinc-100">{selectedCandidate.name}</p>
                        <p className="text-[11px] text-zinc-500">{selectedCandidate.jobRole}</p>
                      </div>
                      <svg viewBox="0 0 60 20" className="h-5 w-14 overflow-visible" fill="none">
                        <path d="M0 10 L60 10" stroke="url(#linkGrad)" strokeWidth="1.5" strokeDasharray="3 3" className="draw-path is-visible" />
                        <defs>
                          <linearGradient id="linkGrad" x1="0" y1="0" x2="1" y2="0">
                            <stop offset="0%" stopColor="rgba(129,140,248,0.6)" />
                            <stop offset="100%" stopColor="rgba(34,211,238,0.6)" />
                          </linearGradient>
                        </defs>
                      </svg>
                      <AriCore state="ready" size={54} />
                    </div>

                    <div className="hidden md:block h-12 w-px bg-[var(--border)]" />

                    <div className="flex-1 text-center md:text-left">
                      <div className="flex items-center justify-center md:justify-start gap-2 text-[11px] font-mono text-zinc-600">
                        <span>8&ndash;12 Adaptive Questions</span>
                        <span className="text-zinc-800">&middot;</span>
                        <span>4+ Curriculum Areas</span>
                      </div>
                    </div>

                    <button
                      type="button"
                      onClick={handleStart}
                      disabled={isStarting}
                      className="group relative overflow-hidden w-full md:w-auto px-6 py-3 rounded-xl bg-indigo-600 hover:bg-indigo-500 disabled:opacity-50 text-white text-sm font-medium transition-colors flex items-center justify-center gap-2 focus:outline-none focus:ring-2 focus:ring-indigo-400/50 shadow-lg shadow-indigo-600/25 shrink-0"
                    >
                      {isStarting ? (
                        <>
                          <div className="h-3.5 w-3.5 border-2 border-white/30 border-t-white rounded-full animate-spin" />
                          <span>Starting...</span>
                        </>
                      ) : (
                        <>
                          <span className="beam" />
                          <span className="relative">Begin Adaptive Interview</span>
                          <ArrowRight className="relative h-3.5 w-3.5 transition-transform group-hover:translate-x-0.5" />
                        </>
                      )}
                    </button>
                  </div>
                </div>
              )}

              <p className="text-[11px] text-zinc-700 font-mono text-center">
                Sample profiles are provided from the ViCodathon challenge dataset.
              </p>
            </>
          )}
        </div>
      </main>
    </ProductShell>
  );
}

function ProfileCard({
  candidate,
  isSelected,
  onSelect,
  compact = false,
}: {
  candidate: DemoCandidateCard;
  isSelected: boolean;
  onSelect: () => void;
  compact?: boolean;
}) {
  const ref = useRef<HTMLButtonElement>(null);

  const onMove = (e: React.PointerEvent) => {
    const el = ref.current;
    if (!el) return;
    const rect = el.getBoundingClientRect();
    el.style.setProperty("--mx", `${((e.clientX - rect.left) / rect.width) * 100}%`);
    el.style.setProperty("--my", `${((e.clientY - rect.top) / rect.height) * 100}%`);
  };

  return (
    <button
      ref={ref}
      type="button"
      onClick={onSelect}
      onPointerMove={onMove}
      className={`group relative w-full h-full overflow-hidden rounded-2xl border text-left transition-all duration-300 edge-glow focus:outline-none focus:ring-2 focus:ring-indigo-500/50 ${
        compact ? "p-4" : "p-6"
      } ${
        isSelected
          ? "border-indigo-500/40 bg-indigo-500/[0.06] shadow-lg shadow-indigo-600/15"
          : "border-[var(--border)] bg-[var(--surface)]/70 hover:border-indigo-500/30"
      }`}
    >
      {/* Mouse-reactive glow */}
      <span
        className="pointer-events-none absolute inset-0 opacity-0 transition-opacity duration-300 group-hover:opacity-100"
        style={{
          background:
            "radial-gradient(220px circle at var(--mx, 50%) var(--my, 50%), rgba(139,92,246,0.14), transparent 65%)",
        }}
      />
      {/* Gradient edge on selection */}
      {isSelected && <span className="beam opacity-30" />}

      <div className="relative flex items-start justify-between gap-3 mb-4">
        <div className="flex items-center gap-3">
          {!compact && (
            <div className="relative shrink-0">
              <AriCore state={isSelected ? "active" : "ready"} size={compact ? 28 : 40} />
            </div>
          )}
          <div>
            <h3 className={`font-semibold text-zinc-100 group-hover:text-white transition-colors ${compact ? "text-sm" : "text-base"}`}>
              {candidate.name}
            </h3>
            <p className="text-[11px] text-zinc-500">{candidate.jobRole}</p>
          </div>
        </div>

        <span
          className={`shrink-0 h-5 w-5 rounded-full border flex items-center justify-center transition-all ${
            isSelected ? "bg-indigo-600 border-indigo-500 scale-100" : "border-zinc-700 scale-90"
          }`}
        >
          {isSelected && <Check className="h-3 w-3 text-white" strokeWidth={3} />}
        </span>
      </div>

      <div className="relative space-y-1.5 text-[11px] text-zinc-500">
        <div className="flex items-center gap-1.5">
          <Briefcase className="h-3 w-3 shrink-0" />
          <span className="text-zinc-400">{candidate.jobRole}</span>
          <span className="text-zinc-700">&middot;</span>
          <span>{candidate.yearsExperience} yrs</span>
        </div>
        <div className="flex items-center gap-1.5">
          <GraduationCap className="h-3 w-3 shrink-0" />
          <span>{candidate.education}</span>
        </div>
      </div>

      {/* Abstract context signal strip */}
      {!compact && (
        <div className="relative mt-4 pt-4 border-t border-[var(--border)] flex items-center gap-1">
          {Array.from({ length: 16 }).map((_, i) => (
            <span
              key={i}
              className="flex-1 rounded-full"
              style={{
                height: `${4 + ((i * 7) % 11)}px`,
                background: isSelected
                  ? `rgba(129,140,248,${0.3 + (i % 4) * 0.15})`
                  : "rgba(113,113,130,0.18)",
                transition: "background 0.4s ease",
              }}
            />
          ))}
        </div>
      )}
    </button>
  );
}
