"use client";

import React, { useState, useEffect } from "react";
import { useRouter } from "next/navigation";
import { ProductShell } from "@/components/ui/ProductShell";
import { InterviewerIdentity } from "@/components/interview/InterviewerIdentity";
import type { DemoCandidateCard } from "@/types/session-dto";
import {
  User,
  Briefcase,
  GraduationCap,
  ArrowRight,
  Sparkles,
  Shield,
  ChevronDown,
} from "lucide-react";

const FEATURED_IDS = ["CAND-003", "CAND-004"];

export default function DemoPage() {
  const router = useRouter();
  const [candidates, setCandidates] = useState<DemoCandidateCard[]>([]);
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [isStarting, setIsStarting] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [showAll, setShowAll] = useState(false);

  useEffect(() => {
    async function loadCandidates() {
      try {
        const res = await fetch("/api/demo/candidates");
        const data = await res.json();
        if (data.success) {
          setCandidates(data.candidates);
        } else {
          setError("Failed to load candidate profiles.");
        }
      } catch {
        setError("Failed to load candidate profiles.");
      } finally {
        setIsLoading(false);
      }
    }
    loadCandidates();
  }, []);

  const handleStart = async () => {
    if (!selectedId || isStarting) return;
    setIsStarting(true);
    setError(null);

    try {
      const res = await fetch("/api/demo/start", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ candidateId: selectedId }),
      });

      const data = await res.json();

      if (!res.ok || !data.success) {
        throw new Error(data.error || "Failed to start session.");
      }

      router.push(`/interview/${data.sessionId}`);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to start session.");
      setIsStarting(false);
    }
  };

  const featured = candidates.filter((c) => FEATURED_IDS.includes(c.id));
  const others = candidates.filter((c) => !FEATURED_IDS.includes(c.id));
  const selectedCandidate = candidates.find((c) => c.id === selectedId);

  return (
    <ProductShell activeRoute="demo">
      <main className="flex-1 max-w-5xl mx-auto w-full px-4 md:px-8 py-8 md:py-12 space-y-8">
        {/* Header */}
        <div className="text-center space-y-3">
          <div className="inline-flex items-center gap-2 px-3.5 py-1.5 rounded-full border border-indigo-500/30 bg-indigo-500/10 text-indigo-300 text-xs font-mono font-medium">
            <Sparkles className="h-3.5 w-3.5 text-indigo-400" />
            JUDGE DEMO
          </div>
          <h1 className="text-3xl md:text-4xl font-extrabold tracking-tight text-zinc-100">
            Experience InterviewOS Live
          </h1>
          <p className="text-sm text-zinc-400 max-w-xl mx-auto leading-relaxed">
            Select a candidate profile to start a fully adaptive technical interview.
            Every question, evaluation, and report is generated by the real engine.
          </p>
        </div>

        {isLoading && (
          <div className="flex items-center justify-center py-16">
            <div className="h-8 w-8 border-2 border-indigo-400/30 border-t-indigo-400 rounded-full animate-spin" />
          </div>
        )}

        {error && !isLoading && (
          <div className="p-4 rounded-xl bg-red-500/10 border border-red-500/30 text-red-300 text-sm text-center">
            {error}
          </div>
        )}

        {!isLoading && candidates.length > 0 && (
          <>
            {/* Featured Demo Profiles */}
            {featured.length > 0 && (
              <div className="space-y-4">
                <div className="flex items-center gap-2">
                  <Shield className="h-4 w-4 text-indigo-400" />
                  <h2 className="text-sm font-semibold text-zinc-200 uppercase tracking-wider font-mono">
                    Featured Demo Profiles
                  </h2>
                </div>
                <p className="text-xs text-zinc-400">
                  Try two profiles to see how InterviewOS starts from different learning contexts.
                </p>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  {featured.map((candidate) => (
                    <CandidateCard
                      key={candidate.id}
                      candidate={candidate}
                      isSelected={candidate.id === selectedId}
                      onSelect={() => setSelectedId(candidate.id)}
                    />
                  ))}
                </div>
              </div>
            )}

            {/* View All */}
            {others.length > 0 && (
              <div className="space-y-4">
                <button
                  type="button"
                  onClick={() => setShowAll(!showAll)}
                  className="flex items-center gap-2 text-xs font-mono text-zinc-400 hover:text-zinc-200 transition-colors"
                >
                  <ChevronDown className={`h-3.5 w-3.5 transition-transform ${showAll ? "rotate-180" : ""}`} />
                  <span>{showAll ? "Hide" : "View all"} demo profiles ({others.length})</span>
                </button>

                {showAll && (
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    {others.map((candidate) => (
                      <CandidateCard
                        key={candidate.id}
                        candidate={candidate}
                        isSelected={candidate.id === selectedId}
                        onSelect={() => setSelectedId(candidate.id)}
                      />
                    ))}
                  </div>
                )}
              </div>
            )}

            {/* Lobby Preview */}
            {selectedCandidate && (
              <div className="p-6 rounded-2xl border border-zinc-800 bg-zinc-900/60 space-y-6 motion-safe:animate-in motion-safe:fade-in motion-safe:duration-200">
                <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 border-b border-zinc-800/80 pb-5">
                  <InterviewerIdentity size="md" statusText="Senior AI Systems Interviewer" />
                  <div className="flex items-center gap-3 text-xs font-mono text-zinc-400">
                    <span className="px-2.5 py-1 rounded bg-zinc-800 border border-zinc-700/60">
                      Format: 8-12 Questions
                    </span>
                    <span className="px-2.5 py-1 rounded bg-zinc-800 border border-zinc-700/60">
                      Curriculum: AI Engineering
                    </span>
                  </div>
                </div>

                <div className="flex flex-col sm:flex-row items-center justify-between gap-4">
                  <div className="text-center sm:text-left">
                    <p className="text-sm text-zinc-200 font-medium">
                      Interview: {selectedCandidate.name}
                    </p>
                    <p className="text-xs text-zinc-400">{selectedCandidate.jobRole}</p>
                  </div>

                  <button
                    type="button"
                    onClick={handleStart}
                    disabled={isStarting}
                    className="w-full sm:w-auto px-6 py-3 rounded-xl bg-indigo-600 hover:bg-indigo-500 active:bg-indigo-700 disabled:opacity-50 text-white text-sm font-semibold transition-all shadow-md shadow-indigo-600/30 flex items-center justify-center gap-2 focus:outline-none focus:ring-2 focus:ring-indigo-400"
                  >
                    {isStarting ? (
                      <>
                        <div className="h-4 w-4 border-2 border-white/30 border-t-white rounded-full animate-spin" />
                        <span>Creating Session...</span>
                      </>
                    ) : (
                      <>
                        <span>Start Interview</span>
                        <ArrowRight className="h-4 w-4" />
                      </>
                    )}
                  </button>
                </div>
              </div>
            )}
          </>
        )}
      </main>
    </ProductShell>
  );
}

function CandidateCard({
  candidate,
  isSelected,
  onSelect,
}: {
  candidate: DemoCandidateCard;
  isSelected: boolean;
  onSelect: () => void;
}) {
  return (
    <button
      type="button"
      onClick={onSelect}
      className={`p-5 rounded-2xl border text-left transition-all relative group flex flex-col justify-between focus:outline-none focus:ring-2 focus:ring-indigo-500 ${
        isSelected
          ? "bg-gradient-to-br from-indigo-950/40 via-zinc-900 to-zinc-900 border-indigo-500/60 shadow-lg shadow-indigo-950/30 ring-1 ring-indigo-500/30"
          : "bg-zinc-900/50 border-zinc-800/80 hover:border-zinc-700 hover:bg-zinc-900/80"
      }`}
    >
      <div className="flex items-start justify-between mb-3">
        <div className="flex items-center gap-3">
          <div
            className={`h-10 w-10 rounded-xl flex items-center justify-center font-bold text-sm transition-colors ${
              isSelected ? "bg-indigo-600 text-white" : "bg-zinc-800 text-zinc-300 group-hover:bg-zinc-700"
            }`}
          >
            <User className="h-5 w-5" />
          </div>
          <div>
            <h3 className="font-semibold text-base text-zinc-100 group-hover:text-white transition-colors">
              {candidate.name}
            </h3>
            <p className="text-xs text-indigo-400 font-mono">{candidate.id}</p>
          </div>
        </div>

        <div
          className={`h-6 w-6 rounded-full border flex items-center justify-center transition-colors ${
            isSelected ? "bg-indigo-600 border-indigo-500 text-white" : "border-zinc-700 bg-zinc-800/50"
          }`}
        >
          {isSelected && (
            <svg className="h-3.5 w-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round">
              <polyline points="20 6 9 17 4 12" />
            </svg>
          )}
        </div>
      </div>

      <div className="space-y-2 text-xs text-zinc-400 border-t border-zinc-800/60 pt-3 mt-1">
        <div className="flex items-center gap-2">
          <Briefcase className="h-3.5 w-3.5 text-zinc-400 shrink-0" />
          <span className="text-zinc-300 font-medium">{candidate.jobRole}</span>
          <span className="text-zinc-600">&middot;</span>
          <span>{candidate.yearsExperience} years exp</span>
        </div>
        <div className="flex items-center gap-2">
          <GraduationCap className="h-3.5 w-3.5 text-zinc-400 shrink-0" />
          <span>{candidate.education}</span>
        </div>
      </div>
    </button>
  );
}
